version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - DB_FILE_PATH=/usr/src/node-app/db/sunshine # full path
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
