/**
 * User test fixtures for use with Knex/SQLite.
 *
 * Usage:
 * const { userOne, userTwo, admin, insertUsers } = require('../fixtures/user.fixture');
 *
 * // To insert users:
 * const users = await insertUsers([userOne, userTwo]);
 * const userOneId = users[0].id;
 *
 * Note: IDs are auto-generated by SQLite.
 * You should get the actual IDs after insertion from the returned objects.
 */

const faker = require('faker');
const User = require('../../src/models/user.model');

const userOne = {
  id: 1,
  name: faker.name.findName(),
  email: faker.internet.email().toLowerCase(),
  password: 'password1',
  role: 'user',
  isEmailVerified: 0,
};

const userTwo = {
  id: 2,
  name: faker.name.findName(),
  email: faker.internet.email().toLowerCase(),
  password: 'password1',
  role: 'user',
  isEmailVerified: 0,
};

const userThree = {
  id: 3,
  name: faker.name.findName(),
  email: faker.internet.email().toLowerCase(),
  password: 'password1',
  role: 'user',
  isEmailVerified: 0,
};

const admin = {
  id: 4,
  name: faker.name.findName(),
  email: faker.internet.email().toLowerCase(),
  password: 'password1',
  role: 'admin',
  isEmailVerified: 0,
};

const insertUsers = async (users) => {
  const createdUsers = await Promise.all(users.map((user) => User.create({ ...user })));
  return createdUsers;
};

module.exports = {
  userOne,
  userTwo,
  userThree,
  admin,
  insertUsers,
};
